

export default [
  'arrowFunctions',
  'binaryLiterals',
  'blockBindings',
  'classes',
  'defaultParams',
  'destructuring',
  'forOf',
  'generators',
  'modules',
  'objectLiteralComputedProperties',
  'objectLiteralDuplicateProperties',
  'objectLiteralShorthandMethods',
  'objectLiteralShorthandProperties',
  'octalLiterals',
  'regexUFlag',
  'regexYFlag',
  'spread',
  'superInFunctions',
  'templateStrings',
  'unicodeCodePointEscapes',
  'globalReturn',
  'jsx',
];
